server:
  port: 8080

spring:
  application:
    name: querydsl
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:mysql://localhost:3306/querydsl?autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 9269
    hikari:
      minimumIdle: 5
      maximumPollSize: 20
      idleTimeout: 30000
      pollName: SpringBootJPAHikariCP
      maxLifetime: 2000000
      connectionTimeout: 30000

logging:
  level:
    root: Info